export type ActivityType = "forum" | "chat" | "dashboard"
export type UserRole = "entrepreneur" | "mentor" | "investor" | "admin"
export type UserType = "entrepreneur" | "supporter" | "official"
export type FileFormat = "pdf" | "doc" | "docx"
export type AccessLevel = "public" | "members" | "premium"
export type MimeType =
    | "application/pdf"
    | "application/msword"
    | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
export type PayMethod = "orange" | "africell" | "bank"
export type DonationStatus = "pending" | "completed" | "failed"
export type ProjectCategory = "Technology" | "Agriculture" | "Business" | "Infrastructure" | "Education" | "Health"
export type ProjectStatus = "Active" | "Completed" | "Funding" | "Suspended"
export type ConnectionRequestStatus = "pending" | "accepted" | "rejected"
export type NetworkEventType = "workshop" | "networking" | "webinar" | "conference" | "meetup"
export type NetworkEventStatus = "upcoming" | "ongoing" | "completed" | "cancelled"
export type ConversationType = "direct" | "group"
export type MessageType = "text" | "image" | "file" | "voice" | "system"
export type NotificationVariant = "info" | "success" | "warning" | "error"
export type NotificationType = "donation_success" | "forum_mention" | "message" | "info" | "connection_request" | "system"
export type DownloadType = "direct" | "preview"
    export type FundingType = "Grant" | "Competition" | "Loan" | "Investment"
export type FundingStatus = "Open" | "Closing Soon" | "Closed"